### ISSUE TITLE
Release v1.0 supporting rails 5.2 - 7, and testing on rails main

### ISSUE THREAD

**Issue by timdiggins** [thredded/db_text_search#11]
Release checklist:

- [x] Update gem version in `version.rb` and `README.md`.
- [x] Update `CHANGELOG.md`.
- [x] Wait for the Travis build to come back green.
- [x] Tag the release and push it to rubygems:

  ```bash
  rake release
  ```

- [x] Copy the release notes from the changelog to [GitHub Releases](https://github.com/thredded/db_text_search/releases).

Draft at: https://github.com/thredded/db_text_search/releases/edit/untagged-eaefc4f69ba4dd583ab0
not sure about binaries

**Comment by timdiggins** [comment]
@glebm could you have a look at the release notes, and let me know if we need binaries and if so what

**Comment by glebm** [comment]
> however we haven't yet removed it from the gemspec, because it might still work

Let's raise the minimum Rails requirement so that people on older Rails versions do not accidentally upgrade to a potentially incompatible release

No need to publish any binaries
