### ISSUE TITLE
PostGIS adapter support

### ISSUE THREAD

**Issue by paulmwatson** [thredded/db_text_search#2]
Any plans to support PostGIS? I will have a look at it but don't want to reinvent the wheel.

**Comment by glebm** [comment]
I don't have plans to build support for it, but would accept it here if you are willing to maintain it.
Though I thought PostGIS just deals with the geo types, leaving the text stuff to regular postgres types?

**Comment by glebm** [comment]
Oh, I see this is probably related to https://github.com/thredded/thredded/issues/349?
If all you need is to match postgis as postgres, I think it would suffice to just change this regex: https://github.com/thredded/db_text_search/blob/0305bc9f1ad6d74e5bb13b5da44ff4a37dd005ff/lib/db_text_search.rb#L27

**Comment by glebm** [comment]
@paulmwatson Did you end up integrating thredded into your app?

**Comment by paulmwatson** [comment]
@glebm afraid not, put on hold and now looking at mailboxer/mailboxer instead

**Comment by oleg-cnnr** [comment]
@glebm I have same problem with postgis adapter in my rails app and I tried to change DbTextSearch module as you suggest. Migration applied successfully. 

I've just changed regexp to 

` when /postgres|postgis/i`

at file 

`config/initializers/thredded/db_text_search.rb`
